apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes-powered real-time analytics platform
name: analytics-platform
version: 0.1.0

# Default values for the analytics platform
replicaCount: 2

image:
  repository: your-docker-repo/analytics-platform
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  pathType: ImplementationSpecific
  hosts:
    - host: chart-example.local
      paths:
        - /

resources: {}
# Limits and requests for CPU and memory can be defined here

nodeSelector: {}

tolerations: []

affinity: {}