# golangci-lint configuration for Real-Time Analytics Platform
# Configuration for golangci-lint v2
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - .git
  skip-files:
    - ".*_test.go"
    - ".*\\.pb\\.go$"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "not allowed"
        allow:
          - $gostd
          - github.com/gin-gonic/gin
          - github.com/stretchr/testify
          - github.com/prometheus/client_golang
          - real-time-analytics-platform
          - processing-engine-go
          - visualization-go
          - tenant-management-go
          - admin-ui-go
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: real-time-analytics-platform
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: real-time-analytics-platform
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  govet:
    shadow: true
    settings:
      printf:
        funcs:
          - (github.com/gin-gonic/gin.Context).JSON
          - (log.Logger).Printf
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
    - path: main\.go
      linters:
        - funlen
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      source: "^//go:generate "

  exclude-use-default: false
  exclude-case-sensitive: false
  include:
    - EXC0002

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info
