version: '3.8'

services:
  secure-api:
    build:
      context: ./flask-api
      dockerfile: Dockerfile
    image: flask-api:latest
    ports:
      - "5000:5000"
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=sensor-data
      - API_KEY_1=${API_KEY_1:-test-key-1}
      - API_KEY_2=${API_KEY_2:-test-key-2}
    depends_on:
      - kafka
    networks:
      - kafka-network

  data-ingestion:
    build:
      context: ./data-ingestion
      dockerfile: Dockerfile
    image: data-ingestion:latest
    ports:
      - "5001:5000"
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=sensor-data
    depends_on:
      - kafka
    networks:
      - kafka-network

  processing-engine:
    build:
      context: ./processing-engine
      dockerfile: Dockerfile
    image: processing-engine:latest
    ports:
      - "5002:5001"
    depends_on:
      - data-ingestion
      - kafka
    networks:
      - kafka-network

  storage-layer:
    build:
      context: ./storage-layer
      dockerfile: Dockerfile
    image: storage-layer:latest
    ports:
      - "5003:5002"
    depends_on:
      - processing-engine
    networks:
      - kafka-network

  visualization:
    build:
      context: ./visualization
      dockerfile: Dockerfile
    image: visualization:latest
    ports:
      - "5004:5003"
    depends_on:
      - storage-layer
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:3.4.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID:-$(openssl rand -hex 11)}
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge