apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: analytics-platform
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    name: plaintext
  type: ClusterIP