# CI/CD Service Account for GitHub Actions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-deployer
  namespace: analytics-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: analytics-platform
  name: deployer-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: analytics-platform
subjects:
- kind: ServiceAccount
  name: github-actions-deployer
  namespace: analytics-platform
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
