# filepath: /Users/yuliu/real-time-analytics-platform/k8s/clean-ingestion-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-ingestion
  namespace: analytics-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-ingestion
  template:
    metadata:
      labels:
        app: clean-ingestion
    spec:
      containers:
      - name: clean-ingestion
        image: clean-ingestion:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
