apiVersion: v1
kind: Service
metadata:
  name: clean-ingestion-go-service
  namespace: analytics-platform
spec:
  selector:
    app: clean-ingestion-go
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30087
  type: NodePort 