apiVersion: v1
kind: Service
metadata:
  name: clean-ingestion-service
  namespace: analytics-platform
spec:
  selector:
    app: clean-ingestion
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30084
  type: NodePort
