# filepath: /Users/yuliu/real-time-analytics-platform/k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: analytics-platform
data:
  # Docker Compose uses kafka:9092, not kafka-service:9092
  KAFKA_BROKER: "kafka:9092"
  KAFKA_TOPIC: "sensor-data"
  KAFKA_PROCESSED_TOPIC: "processed-data"
  KAFKA_ERROR_TOPIC: "error-data"
  KAFKA_ALERTS_TOPIC: "alerts"
  DATA_INGESTION_PORT: "5000"
  PROCESSING_ENGINE_PORT: "5001"
  STORAGE_LAYER_PORT: "5002"
  VISUALIZATION_PORT: "5003"
  TENANT_MANAGEMENT_PORT: "5004"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "analytics"
  DB_USER: "user"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  MAX_CONNECTIONS: "1000"
  CONNECTION_TIMEOUT: "30"
  READ_TIMEOUT: "60"
  WRITE_TIMEOUT: "60"
  CIRCUIT_BREAKER_THRESHOLD: "5"
  CIRCUIT_BREAKER_TIMEOUT: "60"
