apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-go
  namespace: analytics-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion-go
  template:
    metadata:
      labels:
        app: data-ingestion-go
    spec:
      serviceAccountName: data-ingestion-sa
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: data-ingestion-go
        image: data-ingestion-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: KAFKA_BROKER
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: KAFKA_TOPIC
        - name: BYPASS_AUTH
          value: "false"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: API_KEY_1
        - name: ENABLE_API_AUTH
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3 