apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
  namespace: analytics-platform
spec:
  selector:
    app: data-ingestion
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
  type: NodePort