apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-go-service
  namespace: analytics-platform
spec:
  selector:
    app: data-ingestion-go
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer 