apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  namespace: analytics-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
      - name: data-ingestion
        image: real-time-analytics-platform-data-ingestion:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: kafka-broker
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: kafka-topic
        - name: BYPASS_AUTH
          value: "false"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: false  # Temporarily disable this for debugging
          capabilities:
            drop:
            - ALL
