apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: analytics-platform
spec:
  selector:
    app: flask-api
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30085
  type: NodePort
