apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: analytics-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: flask-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
