apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-prod
  namespace: analytics-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi 