apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: analytics-platform
spec:
  selector:
    app: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
  type: ClusterIP