apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-engine-go
  namespace: analytics-platform
  labels:
    app: processing-engine-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-engine-go
  template:
    metadata:
      labels:
        app: processing-engine-go
    spec:
      serviceAccountName: processing-engine-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: processing-engine-go
        image: golang:1.21-alpine
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "echo 'Starting processing engine' && sleep 3600"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: INPUT_TOPIC
          value: "sensor-data"
        - name: OUTPUT_TOPIC
          value: "processed-data"
        - name: METRICS_PORT
          value: "8000"
        - name: CONSUMER_GROUP
          value: "processing-engine-go"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["echo", "healthy"]
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["echo", "healthy"]
          initialDelaySeconds: 5
          periodSeconds: 5
