apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-engine
  namespace: analytics-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processing-engine
  template:
    metadata:
      labels:
        app: processing-engine
    spec:
      containers:
      - name: processing-engine
        image: real-time-analytics-platform-processing-engine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: processing-engine-port
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: kafka-broker
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: kafka-topic
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: analytics-platform-secrets
              key: API_KEY
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 10
