apiVersion: v1
kind: Service
metadata:
  name: processing-engine-service
  namespace: analytics-platform
spec:
  selector:
    app: processing-engine
  ports:
  - port: 80
    targetPort: 5001
  type: ClusterIP