apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-ingestion-sa
  namespace: analytics-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processing-engine-sa
  namespace: analytics-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-layer-sa
  namespace: analytics-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: visualization-sa
  namespace: analytics-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-management-sa
  namespace: analytics-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minimal-pod-access
  namespace: analytics-platform
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-management-role
  namespace: analytics-platform
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-ingestion-binding
  namespace: analytics-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minimal-pod-access
subjects:
- kind: ServiceAccount
  name: data-ingestion-sa
  namespace: analytics-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processing-engine-binding
  namespace: analytics-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minimal-pod-access
subjects:
- kind: ServiceAccount
  name: processing-engine-sa
  namespace: analytics-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storage-layer-binding
  namespace: analytics-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minimal-pod-access
subjects:
- kind: ServiceAccount
  name: storage-layer-sa
  namespace: analytics-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: visualization-binding
  namespace: analytics-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minimal-pod-access
subjects:
- kind: ServiceAccount
  name: visualization-sa
  namespace: analytics-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-management-binding
  namespace: analytics-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-management-role
subjects:
- kind: ServiceAccount
  name: tenant-management-sa
  namespace: analytics-platform 