apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-layer-pv
  namespace: analytics-platform
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/analytics-platform"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-layer-pvc
  namespace: analytics-platform
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
