apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-layer
  namespace: analytics-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-layer
  template:
    metadata:
      labels:
        app: storage-layer
    spec:
      containers:
      - name: storage-layer
        image: storage-layer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: analytics-platform-secrets
              key: DB_PASSWORD
        - name: STORAGE_LAYER_PORT
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: STORAGE_LAYER_PORT
        volumeMounts:
        - name: storage-volume
          mountPath: /data
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true          
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: storage-volume
        emptyDir: {}  # For development; use PVC for production
