apiVersion: v1
kind: Service
metadata:
  name: tenant-management-go-service
  namespace: analytics-platform
  labels:
    app: tenant-management-go
    component: tenant-management
spec:
  selector:
    app: tenant-management-go
  ports:
  - port: 80
    targetPort: 5010
    protocol: TCP
    name: http
  type: ClusterIP
