apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-management
  namespace: analytics-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-management
  template:
    metadata:
      labels:
        app: tenant-management
    spec:
      serviceAccountName: tenant-management-sa
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: tenant-management
        image: tenant-management:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 5010
        env:
        - name: PLATFORM_MODE
          value: kubernetes
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5010
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5010
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-management-service
  namespace: analytics-platform
spec:
  selector:
    app: tenant-management
  ports:
  - port: 5010
    targetPort: 5010
  type: ClusterIP 