apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization
  namespace: analytics-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visualization
  template:
    metadata:
      labels:
        app: visualization
    spec:
      containers:
      - name: visualization
        image: visualization:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: VISUALIZATION_PORT
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: VISUALIZATION_PORT
        readinessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 10
