apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization
  namespace: analytics-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visualization
  template:
    metadata:
      labels:
        app: visualization
    spec:
      containers:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      - name: visualization
        image: real-time-analytics-platform-visualization:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: visualization-port
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: analytics-platform-secrets
              key: API_KEY
        - name: PROCESSING_ENGINE_URL
          value: "http://processing-engine-service"
        - name: STORAGE_LAYER_URL
          value: "http://storage-layer-service"
        readinessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 10
