apiVersion: v1
kind: Service
metadata:
  name: visualization-go-service
  namespace: analytics-platform
spec:
  selector:
    app: visualization-go
  ports:
  - port: 80
    targetPort: 5003
    nodePort: 30083
  type: NodePort 