apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - garage.yaml
  - scale-topic.yaml
  - ../../base/market-data-services

patches:
  - target:
      kind: Kafka
      name: market-kafka
    patch: |-
      - op: add
        path: /spec/kafka/listeners/0/networkPolicyPeers/-
        value:
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: keda
