apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - garage.yaml
  - scale-topic.yaml
  - ../../base/market-data-services

patches:
  - target:
      kind: Kafka
      name: market-kafka
    patch: |-
      - op: add
        path: /spec/kafka/listeners/0/networkPolicyPeers/-
        value:
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: keda
      - op: add
        path: /spec/entityOperator/topicOperator/startupProbe
        value:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 24
      - op: add
        path: /spec/entityOperator/userOperator/livenessProbe
        value:
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
