apiVersion: v1
kind: Service
metadata:
  name: portfolio-api
  namespace: analytics-apps
  labels:
    app.kubernetes.io/name: portfolio-api
    app.kubernetes.io/part-of: investment-analytics-platform
spec:
  selector:
    app.kubernetes.io/name: portfolio-api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api
  namespace: analytics-apps
  labels:
    app.kubernetes.io/name: portfolio-api
    app.kubernetes.io/part-of: investment-analytics-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: portfolio-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portfolio-api
        app.kubernetes.io/part-of: investment-analytics-platform
    spec:
      serviceAccountName: portfolio-api
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 15
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: local/portfolio-api:slice3
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: market-archive-credentials
          env:
            - name: PORTFOLIO_ID
              value: demo
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
