apiVersion: v1
kind: ServiceAccount
metadata:
  name: synthetic-market-producer
  namespace: analytics-apps
  labels:
    app.kubernetes.io/name: synthetic-market-producer
    app.kubernetes.io/part-of: investment-analytics-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raw-event-archiver
  namespace: analytics-apps
  labels:
    app.kubernetes.io/name: raw-event-archiver
    app.kubernetes.io/part-of: investment-analytics-platform
automountServiceAccountToken: false
