apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-runtime
  namespace: analytics-apps
  labels:
    app.kubernetes.io/part-of: investment-analytics-platform
data:
  AWS_REGION: AWS_REGION_PLACEHOLDER
  S3_BUCKET: S3_BUCKET_PLACEHOLDER
