#!/bin/bash

# Test script to verify the generated kubeconfig works
echo "🧪 Testing the generated kubeconfig..."

# Save the base64 kubeconfig to a temp file for testing
echo "YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIGNsdXN0ZXI6CiAgICBjZXJ0aWZpY2F0ZS1hdXRob3JpdHktZGF0YTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkNha05EUVdVMlowRjNTVUpCWjBsQ1FWUkJUa0puYTNGb2EybEhPWGN3UWtGUmMwWkJSRUZXVFZKTmQwVlJXVVJXVVZGRVJYZHdkR0ZYTlhBS1lUTldhVnBWVGtKTlFqUllSRlJKTVUxRVZYbE5SRWwzVFdwTmQwMXNiMWhFVkUweFRVUlZlRTlVU1hkTmFrMTNUV3h2ZDBaVVJWUk5Ra1ZIUVRGVlJRcEJlRTFMWWxkc2RXRlhkREZaYlZaRVVWUkRRMEZUU1hkRVVWbEtTMjlhU1doMlkwNUJVVVZDUWxGQlJHZG5SVkJCUkVORFFWRnZRMmRuUlVKQlRXVmtDbVV5YjFseE4zUkhWMnRRVUVwUE5HbE1TblJrWVVKVk1YbEhSV2hpWmxsV2VXaEJjVlJ5WVdKc1pXRmthaXN3SzFsUVQzUmFXVmRoTjJ0ck15dFRiMVVLUW5Wa1UwOWlkMjFXVWs1UE0xbHRaVU0xVUVwbmNIcE9WbU4yVEc1T1IxbzRPRXhoVGxNeFN6aGtXRE5wYUVReFNuSjFja2xTUldsRmIyUTFOVU5yZHdvMk9YWTNlbkpPVVZCQ1YyRnRTSEZPTVZOU2Frd3hLekoxTkZoMFRIZGtUelpzWjAxYVZFeHROa3RCZG1GMlpYbGpWM1lyTUhCMFVHbE9aM1J5TDJ4QkNrMW5NMW8wVUhWd2NtRkVjSGRpUkRoRWNESkZjMVZ5YnlzelEzVkhieTluYURSemFVaDZRamRGZW1KSWFtVllWVVExY0VsUlUwSklja05hTTBkdU16TUtlbFZoVlhKdFZsRm1MMjlPTUhGTk1tZFZXRVpIU1hsMFRVVm9hSFZtWVhWMWJuRjVRazlKY2xaaGVubEZVa3NyZWtKdmFYaERhRzg1UjNORllVRXlTQXBRY1hoUlJsWjZhVzE0VFVkbVEyUm5ibWc0UTBGM1JVRkJZVTVvVFVZNGQwUm5XVVJXVWpCUVFWRklMMEpCVVVSQlowdHJUVUl3UjBFeFZXUktVVkZYQ2sxQ1VVZERRM05IUVZGVlJrSjNUVU5DWjJkeVFtZEZSa0pSWTBSQlZFRlFRbWRPVmtoU1RVSkJaamhGUWxSQlJFRlJTQzlOUWpCSFFURlZaRVJuVVZjS1FrSlNjbmxQYVZkRVFucHZkakZzWTIxbFpXc3dSMFZpWW1ScWFGZHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVYTkdRVUZQUTBGUlJVRktiR2d4U1cwMWJBcHpjelUwWVVsVWNVVTJMMU41ZFdabFRrZFRVRkkzTldzM1VWZE9RMjk0VXl0RWVUQTFOMElyV1RCTFJVWkpVM1JGV1RWa2JFeGFOVTlCYlVOb1J6ZDJDbFV6TWxGVWJ6SnNZV1ZwWVVWbVQyRnRhbGhqVEVsbGRtWkJhVEZNYVdwVmFtbEhhWE5FZVM5eFMxVjNOVEZhVTI4cmVrNVpaMlUwY1ZwaU1UTk1SVVVLZW1oUGJ6bHlaMVk1VFRSdWMyMUNRakpWYzBOM05tRXhORGxSZFV0Rk1UbHlLMkl3V2tOS2JHSTRVRFJHUjBSclFuSTVWRVJrTVdSdFkxbFRWRXBuWWdvNFJsVm9NbGcyUjFVNVYzSTBiRnBEUlVWa1ltTm9VRTltYjJwTFF6WnJVemRQY25oMVYyUTJjek0yY1ZsVWNETjBabGRFY3pkSmVVeEZVRlp2WjJreUNrcGFUa1l4UTNGV1NUWTNlREpoV0Uxc2FIbG9aSGdyU0Znd1V6bDJMMWxUUkdOTU16aHVhamRwYkhNMGJpOUdNWHBvTkdRM01saGxaMmgyTjA1cFJrSUtRbEZrTkRSNU9GSTNTV1JGUmtFOVBRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0KICAgIHNlcnZlcjogaHR0cHM6Ly8xMjcuMC4wLjE6NTA5MTQKICBuYW1lOiAKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IAogICAgbmFtZXNwYWNlOiBhbmFseXRpY3MtcGxhdGZvcm0KICAgIHVzZXI6IGdpdGh1Yi1hY3Rpb25zLWRlcGxveWVyCiAgbmFtZTogZ2l0aHViLWFjdGlvbnMtY29udGV4dApjdXJyZW50LWNvbnRleHQ6IGdpdGh1Yi1hY3Rpb25zLWNvbnRleHQKdXNlcnM6Ci0gbmFtZTogZ2l0aHViLWFjdGlvbnMtZGVwbG95ZXIKICB1c2VyOgogICAgdG9rZW46IGV5SmhiR2NpT2lKU1V6STFOaUlzSW10cFpDSTZJblp0VUhwWGIzaHhMWE5mYmtOMFZFWlhVRTlMTUVkMVVsQjNZbkZFVFdwQ1lrRkZXWE00TVVoa01Ga2lmUS5leUpwYzNNaU9pSnJkV0psY201bGRHVnpMM05sY25acFkyVmhZMk52ZFc1MElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl1WVcxbGMzQmhZMlVpT2lKaGJtRnNlWFJwWTNNdGNHeGhkR1p2Y20waUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sWTNKbGRDNXVZVzFsSWpvaVoybDBhSFZpTFdGamRHbHZibk10WkdWd2JHOTVaWEl0ZEc5clpXNGlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzV1WVcxbElqb2laMmwwYUhWaUxXRmpkR2x2Ym5NdFpHVndiRzk1WlhJaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNTFhV1FpT2lJME9UVmpOak0xTkMwNVkyTmxMVFEwWVRZdFltTmtOeTAyWVRJek16SmlPR0kxWldFaUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZZVzVoYkhsMGFXTnpMWEJzWVhSbWIzSnRPbWRwZEdoMVlpMWhZM1JwYjI1ekxXUmxjR3h2ZVdWeUluMC5HNHJ5UmdwMEtuTmVBMlZabTVzWEU2RDN3NG5PYkNCQVZvaFl4R3EzWkR2djFhdDFQOXdiUUFpeEN5NDVvbVlKUWtPUWtVMkI4ektIbzFlalpzaXR3SUgzdkktN2tQTkpia2ZoN3Nha09zTmhZNTNCSmxjZWpaQXNWTFBNRnlfNUZIZVBaVVdraXQxbHBvWGoyWU9LSGdlM05vRDlxNDIxTlV2bTZ5WlZQeGVnWnpRRm90SDNLaHNBYm1MY3kzM1o3WWR4WjNJYkU1YTduSmEtbDhFdml6TnNCOEhlZUtYb0Y4QnlOMmx3YWkzdW9xRWR3ZS1tdERSUzUzcEJiQXAwdnRFcl9pX0h2UFVzbDJhaWdwWWdMNVN6X1lGcEVqRy13Mm1UOWhmM2xDT2NDSmlYb3VZbUd0bG13eGZlaV9xeTI4NElsQmNBS3RxNjBYOGhoSlA1dHcK" | base64 -d > /tmp/test-kubeconfig

export KUBECONFIG=/tmp/test-kubeconfig

echo "Testing connection with limited service account..."
kubectl get nodes 2>/dev/null && echo "✅ Can connect to cluster" || echo "❌ Cannot connect to cluster"

echo "Testing namespace access..."
kubectl get pods -n analytics-platform 2>/dev/null && echo "✅ Can access analytics-platform namespace" || echo "ℹ️  No pods in analytics-platform namespace (this is expected)"

echo "Testing secret creation permissions..."
kubectl create secret generic test-secret --from-literal=test=value -n analytics-platform --dry-run=client -o yaml > /dev/null && echo "✅ Can create secrets" || echo "❌ Cannot create secrets"

echo "Testing deployment permissions..."
kubectl get deployments -n analytics-platform 2>/dev/null && echo "✅ Can list deployments" || echo "ℹ️  No deployments in analytics-platform namespace (this is expected)"

echo "Testing cluster-level access (should fail)..."
kubectl get namespaces 2>/dev/null && echo "❌ WARNING: Has cluster-level access" || echo "✅ Correctly restricted to namespace"

# Cleanup
rm /tmp/test-kubeconfig
export KUBECONFIG=$HOME/.kube/config

echo "🎯 Test completed!"
